apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-deployment
  labels:
    app: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
        - name: servicea
          image: image-registry.openshift-image-registry.svc:5000/pablo-demo/servicea
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: certs-volume
          configMap:
            name: servicea-certs
---
apiVersion: v1
kind: Service
metadata:
  name: servicea-service
  labels:
    app: servicea
spec:
  type: ClusterIP
  selector:
    app: servicea
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: servicea-service
spec:
  to:
    kind: Service
    name: servicea-service
  port:
    targetPort: 5000